/**

 * Auto-generated types based on API schema

 * Generated by axiosflow

 * @generated

 * @timestamp 2025-01-02T16:35:09.220Z

 */


export interface User {
    id: number;
    name: string;
}


export interface UserRequest {
    name: string;
}